// <auto-generated />
using System;
using APILabb3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APILabb3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230521081732_fixetHobbiesListTable")]
    partial class fixetHobbiesListTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APILabb3.Models.Hobbie", b =>
                {
                    b.Property<int>("HobbieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobbieId"));

                    b.Property<int?>("FK_PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("HobbieId");

                    b.HasIndex("FK_PersonId");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            HobbieId = 1,
                            Summary = "Intresse-beskrivning1",
                            Title = "Intresse1"
                        },
                        new
                        {
                            HobbieId = 2,
                            Summary = "Intresse-beskrivning2",
                            Title = "Intresse2"
                        },
                        new
                        {
                            HobbieId = 3,
                            Summary = "Intresse-beskrivning3",
                            Title = "Intresse3"
                        },
                        new
                        {
                            HobbieId = 4,
                            Summary = "Intresse-beskrivning4",
                            Title = "Intresse4"
                        },
                        new
                        {
                            HobbieId = 5,
                            Summary = "Intresse-beskrivning5",
                            Title = "Intresse5"
                        },
                        new
                        {
                            HobbieId = 6,
                            Summary = "Intresse-beskrivning6",
                            Title = "Intresse6"
                        });
                });

            modelBuilder.Entity("APILabb3.Models.HobbiesList", b =>
                {
                    b.Property<int>("HobbiesListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobbiesListId"));

                    b.Property<int?>("FK_HobbiesId")
                        .HasColumnType("int");

                    b.Property<string>("LinkName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HobbiesListId");

                    b.HasIndex("FK_HobbiesId");

                    b.ToTable("HobbiesLists");
                });

            modelBuilder.Entity("APILabb3.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            FirstName = "Malin1",
                            LastName = "Eriksson1",
                            PhoneNumber = ""
                        },
                        new
                        {
                            PersonId = 2,
                            FirstName = "Malin2",
                            LastName = "Eriksson2",
                            PhoneNumber = ""
                        },
                        new
                        {
                            PersonId = 3,
                            FirstName = "Malin3",
                            LastName = "Eriksson3",
                            PhoneNumber = ""
                        },
                        new
                        {
                            PersonId = 4,
                            FirstName = "Malin4",
                            LastName = "Eriksson4",
                            PhoneNumber = ""
                        },
                        new
                        {
                            PersonId = 5,
                            FirstName = "Malin5",
                            LastName = "Eriksson5",
                            PhoneNumber = ""
                        },
                        new
                        {
                            PersonId = 6,
                            FirstName = "Malin6",
                            LastName = "Eriksson6",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("APILabb3.Models.Hobbie", b =>
                {
                    b.HasOne("APILabb3.Models.Person", "Persons")
                        .WithMany("Hobbies")
                        .HasForeignKey("FK_PersonId");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("APILabb3.Models.HobbiesList", b =>
                {
                    b.HasOne("APILabb3.Models.Hobbie", "Hobbies")
                        .WithMany("HobbiesLists")
                        .HasForeignKey("FK_HobbiesId");

                    b.Navigation("Hobbies");
                });

            modelBuilder.Entity("APILabb3.Models.Hobbie", b =>
                {
                    b.Navigation("HobbiesLists");
                });

            modelBuilder.Entity("APILabb3.Models.Person", b =>
                {
                    b.Navigation("Hobbies");
                });
#pragma warning restore 612, 618
        }
    }
}
